# Generated by Django 4.1.3 on 2023-03-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('recommender_flag', models.BooleanField(default=True)),
                ('scenario_planner_flag', models.BooleanField()),
                ('category_id', models.IntegerField()),
                ('promo_type_id', models.IntegerField()),
                ('promo_type_code', models.CharField(max_length=10)),
                ('n_store', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'item_master',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('market_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('market_name', models.CharField(max_length=200, null=True)),
                ('market_code', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
        migrations.CreateModel(
            name='OfferHierMaster',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ohm_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ohm_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('ohm_code', models.CharField(blank=True, max_length=255, null=True)),
                ('ohm_level', models.IntegerField(blank=True, null=True)),
                ('ohm_parent_id', models.IntegerField(blank=True, null=True)),
                ('is_reportable', models.BooleanField(default=True)),
                ('ohm_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer_hier_master',
            },
        ),
        migrations.CreateModel(
            name='PromoChannel',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('promo_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('promo_name', models.CharField(max_length=200, null=True)),
                ('channel_code', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'promo_channel',
            },
        ),
        migrations.CreateModel(
            name='PromoTypes',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('promo_type_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='promo_type_id')),
                ('promo_type_name', models.CharField(max_length=200, null=True, verbose_name='promo_type_name')),
                ('promo_type_code', models.CharField(max_length=200, null=True, verbose_name='promo_type_code')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'promo_types',
            },
        ),
        migrations.CreateModel(
            name='scenario_master',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('scenario_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('package_id', models.IntegerField(default=None)),
                ('scenario_name', models.CharField(max_length=200)),
                ('weight_1', models.FloatField(default=None)),
                ('weight_2', models.FloatField(default=None)),
                ('weight_3', models.FloatField(default=None)),
            ],
            options={
                'db_table': 'scenario_master',
            },
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='status_id')),
                ('status_name', models.CharField(max_length=200, null=True, verbose_name='status_name')),
                ('status_code', models.IntegerField(choices=[('1', 'Saved'), ('2', 'Submitted'), ('3', 'Completed')], default='1', verbose_name='status_code')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'status_master',
            },
        ),
        migrations.CreateModel(
            name='UserGeoMapping',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hierarchy_code', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_geo_mapping',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('language_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('language_code', models.CharField(max_length=200, null=True)),
                ('language_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('currency_symbol', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('default_language', models.CharField(blank=True, max_length=1000, null=True)),
                ('region_id', models.ForeignKey(db_column='region_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='LanguageRegion', to='common.market')),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
