# Generated by Django 4.1.3 on 2023-04-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='promo_type_id',
            field=models.ForeignKey(db_column='promo_type_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Promotypes', to='common.promotypes'),
        ),
    ]
