# Generated by Django 4.1.3 on 2023-04-05 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_item_promo_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'product_category',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='category_id',
            field=models.ForeignKey(db_column='category_id', default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Productcategory', to='common.category'),
        ),
    ]
