# Generated by Django 4.1.3 on 2023-04-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_category_alter_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='promotypes',
            old_name='promo_type_id',
            new_name='id',
        ),
    ]
