# Generated by Django 4.1.3 on 2023-04-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_item_promo_type_code_alter_item_category_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferHierMaster',
        ),
        migrations.DeleteModel(
            name='PromoChannel',
        ),
        migrations.DeleteModel(
            name='scenario_master',
        ),
        migrations.DeleteModel(
            name='StatusMaster',
        ),
        migrations.DeleteModel(
            name='UserGeoMapping',
        ),
    ]
